version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - uploads-data:/app/public/uploads
    environment:
      - NODE_ENV=production
    command: npm start

volumes:
  uploads-data:
