services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - hypertube_net
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - hypertube_net


  web:
    build:
      context: .
    container_name: hypertube_web
    restart: always
    ports:
      - "3000:3000"
    networks:
      - hypertube_net
    volumes:
      - uploads-data:/app/build/public/uploads
    depends_on:
      - db
    command: npm start

networks:
  hypertube_net:
    driver: bridge
