services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  postgres_data:
